const ENV_TILE_ROOT = "sprites/kenney_pixel-platformer/Tiles";
const TINY_TOWN_TILE_ROOT = "sprites/kenney_tiny-town/Tiles";

function tilePath(root, index) {
  return `${root}/tile_${String(index).padStart(4, "0")}.png`;
}

function spriteId(tileName) {
  return `env_${tileName}`;
}

const BASE_ENV_TILE_ORDER = Object.freeze({
  grass_single: 0,
  grass_1: 1,
  grass_2: 2,
  grass_3: 3,
  ground_1: 4,
  ground_2: 5,
  ground_single: 6,
  stone_big: 7,
  stone_small: 8,
  special: 9,
  special_warning: 10,
  special_o: 11,
  mushroom_1: 12,
  mushroom_2: 13,
  mushroom_3: 14,
  mushroom_4: 15,
  bush_single: 16,
  bush_tl: 17,
  bush_t: 18,
  bush_tr: 19,
  grass_single_1: 20,
  grass_4: 21,
  grass_5: 22,
  grass_6: 23,
  ground_tr: 24,
  ground_tl: 25,
  crate: 26,
  key: 27,
  lock: 28,
  special_b: 29,
  special_b_warning: 30,
  special_b_o: 31,
  trunk_l: 32,
  water_1: 33,
  river_t1: 34,
  river_t2: 35,
  bush_1t: 36,
  bush_l: 37,
  bush_c: 38,
  bush_r: 39,
  sand_1: 40,
  sand_2: 41,
  sand_3: 42,
  sand_4: 43,
  heat_1: 44,
  heat_2: 45,
  heat_3: 46,
  block: 47,
  block_l: 48,
  block_c: 49,
  block_r: 50,
  stair_t: 51,
  trunk_l2: 52,
  water_2: 53,
  water_3: 54,
  water_4: 55,
  bush_2t: 56,
  bush_2l: 57,
  bush_2c: 58,
  bush_2r: 59,
  sand_5: 60,
  sand_6: 61,
  sand_7: 62,
  sand_8: 63,
  lever_1: 64,
  lever_2: 65,
  lever_3: 66,
  diamond: 67,
  spikes: 68,
  rope_t: 69,
  hook: 70,
  stair: 71,
  trunk_l_base: 72,
  water_center: 73,
  river_b1: 74,
  river_b2: 75,
  bush_single_2: 76,
  bush_1l: 77,
  bush_1c: 78,
  bush_1r: 79,
  snow_1: 80,
  snow_2: 81,
  snow_3: 82,
  snow_4: 83,
  sign_board_1: 84,
  sign_board_2: 85,
  sign_board_3: 86,
  sign_arrow_l: 87,
  sign_arrow_r: 88,
  rope_1: 89,
  pipe_orange_l: 90,
  pipe_orange_c: 91,
  pipe_orange_r: 92,
  pipe_blue_tl: 93,
  pipe_blue_tr: 94,
  pipe_blue_c: 95,
  pipe_blue_corner_tl: 93,
  pipe_blue_corner_tr: 94,
  pipe_blue_vertical_start: 95,
  button_green: 96,
  plant_1: 97,
  plant_hanging_l: 98,
  plant_hanging_r: 99,
  snow_ground_1: 100,
  snow_ground_2: 101,
  snow_ground_3: 102,
  snow_ground_4: 103,
  ground_single: 104,
  obstacle_fence_1: 105,
  obstacle_fence_2: 106,
  button_red_1: 107,
  button_red_2: 108,
  button_red_3: 109,
  button_orange: 110,
  flag_1: 111,
  flag_2: 112,
  pipe_cyan_tl: 113,
  pipe_cyan_tr: 114,
  pipe_cyan_c: 115,
  pipe_blue_corner_bl: 113,
  pipe_blue_corner_br: 114,
  pipe_blue_vertical_center: 115,
  tree_branch_l: 116,
  tree_branch_c: 117,
  tree_branch_r: 118,
  tree_platform: 119,
  ground_fill_2: 120,
  ground_fill_3: 121,
  ground_fill_4: 122,
  ground_fill_5: 123,
  plant_2: 124,
  plant_3: 125,
  tree_1: 126,
  plant_cactus: 127,
  obstacle_torch_red: 128,
  obstacle_torch_yellow: 129,
  door_1: 130,
  rope_2: 131,
  cloud_blue_l: 132,
  cloud_blue_c: 133,
  cloud_blue_r: 134,
  pipe_blue_horizontal_start: 132,
  pipe_blue_horizontal_center: 133,
  pipe_blue_horizontal_end: 134,
  pipe_blue_vertical_end: 135,
  cloud_blue_b: 135,
  tree_branch_snow_l: 136,
  tree_branch_snow_c: 137,
  tree_branch_snow_r: 138,
  tree_platform_snow: 139,
  ground_fill_6: 140,
  ground_fill_7: 141,
  ground_fill_8: 142,
  ground_fill_9: 143,
  obstacle_bat: 144,
  obstacle_snowman: 145,
  platform_wood_1: 146,
  platform_wood_2: 147,
  cloud_small_blue: 148,
  cloud_small_white: 149,
  door_2: 150,
  coin_1: 151,
  key_1: 152,
  cloud_white_l: 153,
  cloud_white_c: 154,
  cloud_white_r: 155,
  cloud_white_s: 156,
  number_dot: 157,
  number_x: 158,
  number_div: 159,
  number_0: 160,
  number_1: 161,
  number_2: 162,
  number_3: 163,
  number_4: 164,
  number_5: 165,
  number_6: 166,
  number_7: 167,
  number_8: 168,
  number_9: 169,
  number_alt_0: 170,
  number_alt_1: 171,
  number_alt_2: 172,
  number_alt_3: 173,
  number_alt_4: 174,
  number_alt_5: 175,
  number_alt_6: 176,
  number_alt_7: 177,
  number_alt_8: 178,
  number_alt_9: 179,
});

export const TINY_TOWN_TILE_ORDER = Object.freeze(
  {
    tiny_ground_top_left: 0,
    tiny_ground_top_center: 1,
    tiny_ground_top_right: 2,
    tiny_ground_top_single: 3,
    tiny_ground_mid_left: 12,
    tiny_ground_mid_center: 13,
    tiny_ground_mid_right: 14,
    tiny_ground_mid_single: 15,
    tiny_ground_bottom_left: 24,
    tiny_ground_bottom_center: 25,
    tiny_ground_bottom_right: 26,
    tiny_ground_bottom_single: 27,
    tiny_plants_top_1: 3,
    tiny_plants_top_2: 4,
    tiny_plants_top_3: 5,
    tiny_plants_top_4: 6,
    tiny_plants_top_5: 7,
    tiny_plants_top_6: 8,
    tiny_plants_top_7: 9,
    tiny_plants_top_8: 10,
    tiny_plants_top_9: 11,
    tiny_plants_mid_1: 15,
    tiny_plants_mid_2: 16,
    tiny_plants_mid_3: 17,
    tiny_plants_mid_4: 18,
    tiny_plants_mid_5: 19,
    tiny_plants_mid_6: 20,
    tiny_plants_mid_7: 21,
    tiny_plants_mid_8: 22,
    tiny_plants_mid_9: 23,
    tiny_plants_bottom_1: 27,
    tiny_plants_bottom_2: 28,
    tiny_plants_bottom_3: 29,
    tiny_plants_bottom_4: 30,
    tiny_plants_bottom_5: 31,
    tiny_plants_bottom_6: 32,
    tiny_plants_bottom_7: 33,
    tiny_plants_bottom_8: 34,
    tiny_plants_bottom_9: 35,
    tiny_roof_top_grey_left: 48,
    tiny_roof_top_grey_center: 49,
    tiny_roof_top_grey_right: 50,
    tiny_roof_top_grey_chimney: 51,
    tiny_roof_top_red_left: 52,
    tiny_roof_top_red_center: 53,
    tiny_roof_top_red_right: 54,
    tiny_roof_top_red_chimney: 55,
    tiny_roof_bottom_grey_left: 60,
    tiny_roof_bottom_grey_center: 61,
    tiny_roof_bottom_grey_right: 62,
    tiny_roof_bottom_grey_dormer: 63,
    tiny_roof_bottom_red_left: 64,
    tiny_roof_bottom_red_center: 65,
    tiny_roof_bottom_red_right: 66,
    tiny_roof_bottom_red_dormer: 67,
    tiny_house_brown_wall_left: 72,
    tiny_house_brown_wall_center: 73,
    tiny_house_brown_door_open: 74,
    tiny_house_brown_wall_right: 75,
    tiny_house_gray_wall_left: 76,
    tiny_house_gray_wall_center: 77,
    tiny_house_gray_door_open: 78,
    tiny_house_gray_wall_right: 79,
    tiny_house_brown_window: 84,
    tiny_house_brown_door_closed: 85,
    tiny_house_brown_door_closed_right: 86,
    tiny_house_brown_door_closed_left: 87,
    tiny_house_gray_window: 88,
    tiny_house_gray_door_closed: 89,
    tiny_house_gray_door_closed_right: 90,
    tiny_house_gray_door_closed_left: 91,
  },
);

export const ENV_TILE_ORDER = Object.freeze({
  ...BASE_ENV_TILE_ORDER,
  ...TINY_TOWN_TILE_ORDER,
});

function createSpriteEntries(tileOrder, root) {
  return Object.fromEntries(
    Object.entries(tileOrder).map(([tileName, tileIndex]) => [
      tileName,
      {
        sprite: spriteId(tileName),
        path: tilePath(root, tileIndex),
      },
    ]),
  );
}

export const ENV_TILE_SPRITES = Object.freeze(
  {
    ...createSpriteEntries(BASE_ENV_TILE_ORDER, ENV_TILE_ROOT),
    ...createSpriteEntries(TINY_TOWN_TILE_ORDER, TINY_TOWN_TILE_ROOT),
  },
);

export function loadEnvironmentTileAssets(k) {
  Object.values(ENV_TILE_SPRITES).forEach(({ sprite, path }) => {
    k.loadSprite(sprite, path);
  });
}

export function getEnvironmentTileSprite(tileName) {
  const tile = ENV_TILE_SPRITES[tileName];
  if (!tile) {
    throw new Error(`Environment tile "${tileName}" non definito.`);
  }
  return tile.sprite;
}
