const FARM_ENV_TILE_ROOT = "sprites/kenney_pixel-platformer-farm-expansion/Tiles";

function tilePath(index) {
  return `${FARM_ENV_TILE_ROOT}/tile_${String(index).padStart(4, "0")}.png`;
}

function spriteId(tileName) {
  return `env_farm_${tileName}`;
}

export const FARM_ENV_TILE_ORDER = Object.freeze({
  soil_single: 0,
  soil_single_left: 1,
  soil_single_center: 2,
  soil_single_right: 3,
  pumpkin: 4,
  pumpkin_carved: 5,
  hay_bale_single: 6,
  hay_bale_left: 7,
  hay_bale_right: 8,
  hay_roll: 9,
  hay_bale_small: 6,
  hay_bale_wide_left: 7,
  hay_bale_wide_right: 8,
  hay_bale_round: 9,
  tree_crown_single_top: 12,
  tree_crown_wide_top_left: 13,
  tree_crown_wide_top_center: 14,
  tree_crown_wide_top_right: 15,
  soil_top_multi_single: 16,
  soil_top_left: 17,
  soil_top_center: 18,
  soil_top_right: 19,
  soil_hill_left: 24,
  soil_hill_right: 25,
  sunflower: 20,
  shovel: 21,
  tree_crown_single_upper: 28,
  tree_crown_wide_mid_left: 29,
  tree_crown_wide_mid_center: 30,
  tree_crown_wide_mid_right: 31,
  soil_center_single: 32,
  soil_center_left: 33,
  soil_center_center: 34,
  soil_center_right: 35,
  tree_crown_single_lower: 44,
  tree_crown_wide_bottom_left: 45,
  tree_crown_wide_bottom_center: 46,
  tree_crown_wide_bottom_right: 47,
  crop_carrot: 56,
  crop_tomatoes: 57,
  crop_wheat: 58,
  crop_corn: 59,
  tree_crown_single_bottom: 60,
  tree_crown_single_horizontal_left: 61,
  tree_crown_single_horizontal_center: 62,
  tree_crown_single_horizontal_right: 63,
  soil_bottom_single: 48,
  soil_bottom_left: 49,
  soil_bottom_center: 50,
  soil_bottom_right: 51,
  greenhouse_open_top_left: 64,
  greenhouse_open_top_center_left: 65,
  greenhouse_open_top_center_right: 66,
  greenhouse_open_top_right: 67,
  greenhouse_closed_top_left: 68,
  greenhouse_closed_top_center_left: 69,
  greenhouse_closed_top_center_right: 70,
  greenhouse_closed_top_right: 71,
  crop_leaf_small: 72,
  crop_leaf_tall: 73,
  crop_wheat_tall: 74,
  crop_vine: 75,
  farm_sign_post: 76,
  hanging_pot: 78,
  greenhouse_open_mid_left: 80,
  greenhouse_open_mid_center_left: 81,
  greenhouse_open_mid_center_right: 82,
  greenhouse_open_mid_right: 83,
  greenhouse_closed_mid_left: 84,
  greenhouse_closed_mid_center_left: 85,
  greenhouse_closed_mid_center_right: 86,
  greenhouse_closed_mid_right: 87,
  sprout_small: 88,
  sprout_tall: 89,
  sprout_leafy: 90,
  sprout_vine: 91,
  tree_trunk_left: 92,
  tree_trunk_right: 93,
  tree_trunk_branch_both: 93,
  tree_branch_stub: 94,
  tree_branch_horizontal: 95,
  greenhouse_open_bottom_left: 96,
  greenhouse_open_bottom_center_left: 97,
  greenhouse_open_bottom_center_right: 98,
  greenhouse_open_bottom_right: 99,
  greenhouse_closed_bottom_left: 100,
  greenhouse_closed_bottom_center_left: 101,
  greenhouse_closed_bottom_center_right: 102,
  greenhouse_closed_bottom_right: 103,
  tree_large_trunk_top: 76,
  tree_large_canopy_connector: 77,
  tree_branch_leaf_end_left: 78,
  tree_branch_leaf_center: 79,
  crop_stump: 104,
  crop_dry_small: 105,
  crop_dry_large: 106,
  crop_corn_tall: 107,
  tree_trunk_branch_left: 108,
  tree_trunk_plain: 109,
  tree_trunk_branch_right: 110,
  tree_trunk_cap_left: 108,
  tree_trunk_mid: 109,
  tree_trunk_fork: 110,
  tree_branch_tip: 111,
  tree_crown_single_mid: 28,
  tree_crown_top_left: 13,
  tree_crown_top_center: 14,
  tree_crown_top_right: 15,
  tree_crown_mid_left: 29,
  tree_crown_mid_center: 30,
  tree_crown_mid_right: 31,
  tree_crown_bottom_left: 45,
  tree_crown_bottom_center: 46,
  tree_crown_bottom_right: 47,
  greenhouse_roof_frame_left: 64,
  greenhouse_roof_frame_center_left: 65,
  greenhouse_roof_frame_center_right: 66,
  greenhouse_roof_frame_right: 67,
  greenhouse_roof_glass_left: 68,
  greenhouse_roof_glass_center_left: 69,
  greenhouse_roof_glass_center_right: 70,
  greenhouse_roof_glass_right: 71,
  greenhouse_wall_upper_left: 80,
  greenhouse_wall_upper_center_left: 81,
  greenhouse_wall_upper_center_right: 82,
  greenhouse_wall_upper_right: 83,
  greenhouse_glass_left: 84,
  greenhouse_glass_door: 85,
  greenhouse_glass_center_right: 86,
  greenhouse_glass_right: 87,
  greenhouse_wall_lower_left: 96,
  greenhouse_wall_lower_center_left: 97,
  greenhouse_wall_lower_center_right: 98,
  greenhouse_wall_lower_right: 99,
  greenhouse_glass_lower_left: 100,
  greenhouse_glass_lower_door: 101,
  greenhouse_glass_lower_center_right: 102,
  greenhouse_glass_lower_right: 103,
});

export const FARM_ENV_TILE_SPRITES = Object.freeze(
  Object.fromEntries(
    Object.entries(FARM_ENV_TILE_ORDER).map(([tileName, tileIndex]) => [
      tileName,
      {
        sprite: spriteId(tileName),
        path: tilePath(tileIndex),
      },
    ]),
  ),
);

export function loadEnvironmentTileFarmAssets(k) {
  Object.values(FARM_ENV_TILE_SPRITES).forEach(({ sprite, path }) => {
    k.loadSprite(sprite, path);
  });
}

export function getEnvironmentTileFarmSprite(tileName) {
  const tile = FARM_ENV_TILE_SPRITES[tileName];
  if (!tile) {
    throw new Error(`Environment farm tile "${tileName}" non definito.`);
  }
  return tile.sprite;
}
